### PR TITLE
feat add rust-libm

### PR DESCRIPTION
**Pull request by Starains320**
the source for the Rust libm crate

Log: add rust-libm
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/132

### CODE REVIEW

**Comment by Starains320** [comment]
@chenchongbiao 老师您好，obs已通过，请检查这个pr

**Comment by Starains320** [comment]
@chenchongbiao 老师您好，请检查一下pr

**Comment by Starains320** [comment]
@chenchongbiao 老师您好，请检查一下pr

**Comment by Starains320** [comment]
@chenchongbiao 老师您好，请检查一下pr

**Comment by Starains320** [comment]
@chenchongbiao 老师您好，请检查一下pr

**Review by chenchongbiao — APPROVED** [review]

**Pull request merged**
